from dataclasses import dataclass
import logging

from app.config import get_settings

try:
    from openai import OpenAI
except Exception:  # pragma: no cover - graceful fallback if package is unavailable
    OpenAI = None


@dataclass
class SQLAgentResult:
    sql: str
    explanation: str


AI4I_SCHEMA_HINT = """
Table: sensor_observations_ai4i
Columns:
- observation_id, source_dataset, source_row_id, product_id, machine_type
- air_temperature_k, process_temperature_k, rotational_speed_rpm
- torque_nm, tool_wear_min, delta_temp_k, power_proxy

Table: failure_labels_ai4i
Columns:
- observation_id, machine_failure, twf, hdf, pwf, osf, rnf

View: ml_training_dataset_ai4i
Columns:
- observation_id, source_row_id, product_id, machine_type
- air_temperature_k, process_temperature_k, rotational_speed_rpm
- torque_nm, tool_wear_min, delta_temp_k, power_proxy, machine_failure
""".strip()


PROMPT_TEMPLATE = """
You are an industrial reliability SQL assistant.
Return ONLY valid PostgreSQL SQL in one statement.
Do not use markdown.

Database schema hint:
{schema_hint}

User question:
{question}
""".strip()


def heuristic_sql(question: str) -> SQLAgentResult:
    q = question.lower()
    if "failure rate" in q or "failure" in q:
        sql = (
            "SELECT o.machine_type, "
            "ROUND(100.0 * AVG(l.machine_failure::int), 2) AS failure_rate_pct "
            "FROM sensor_observations_ai4i o "
            "JOIN failure_labels_ai4i l ON l.observation_id = o.observation_id "
            "GROUP BY o.machine_type "
            "ORDER BY failure_rate_pct DESC"
        )
        explanation = "Computes failure rate by machine type."
        return SQLAgentResult(sql=sql, explanation=explanation)

    if "top" in q and "torque" in q:
        sql = (
            "SELECT source_row_id, product_id, machine_type, torque_nm "
            "FROM sensor_observations_ai4i "
            "ORDER BY torque_nm DESC "
            "LIMIT 20"
        )
        explanation = "Lists highest torque observations for triage."
        return SQLAgentResult(sql=sql, explanation=explanation)

    sql = "SELECT * FROM ml_training_dataset_ai4i ORDER BY source_row_id LIMIT 20"
    explanation = "Fallback sample query to inspect recent rows."
    return SQLAgentResult(sql=sql, explanation=explanation)


def llm_sql(question: str) -> SQLAgentResult:
    settings = get_settings()
    if not settings.openai_api_key or OpenAI is None:
        return heuristic_sql(question)

    client = OpenAI(api_key=settings.openai_api_key)
    prompt = PROMPT_TEMPLATE.format(schema_hint=AI4I_SCHEMA_HINT, question=question)

    try:
        response = client.responses.create(
            model=settings.llm_model,
            input=prompt,
            temperature=0,
        )
    except Exception as exc:  # pragma: no cover - network/auth/runtime fallback
        logging.warning("LLM SQL generation failed; using heuristic fallback: %s", exc)
        return heuristic_sql(question)

    sql = (response.output_text or "").strip()
    if not sql:
        return heuristic_sql(question)

    return SQLAgentResult(
        sql=sql,
        explanation="SQL generated by LLM using current schema hint.",
    )
