from dataclasses import dataclass
from pathlib import Path

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

from app.config import get_settings

try:
    from openai import OpenAI
except Exception:  # pragma: no cover - optional dependency guard
    OpenAI = None


ALLOWED_EXTENSIONS = (".md", ".txt")


@dataclass
class RetrievedChunk:
    source: str
    score: float
    text: str


@dataclass
class KnowledgeIndex:
    chunks: list[str]
    sources: list[str]
    vectorizer: TfidfVectorizer
    matrix: object


def _chunk_text(text: str, chunk_size: int, overlap: int) -> list[str]:
    if chunk_size <= 0:
        return [text]

    cleaned = " ".join(text.split())
    if len(cleaned) <= chunk_size:
        return [cleaned]

    chunks: list[str] = []
    start = 0
    step = max(1, chunk_size - overlap)
    while start < len(cleaned):
        end = start + chunk_size
        chunk = cleaned[start:end].strip()
        if chunk:
            chunks.append(chunk)
        if end >= len(cleaned):
            break
        start += step
    return chunks


def _read_knowledge_documents(knowledge_dir: str, chunk_size: int, overlap: int) -> tuple[list[str], list[str]]:
    base_path = Path(knowledge_dir)
    if not base_path.exists():
        return [], []

    chunks: list[str] = []
    sources: list[str] = []
    for file_path in sorted(base_path.rglob("*")):
        if not file_path.is_file() or file_path.suffix.lower() not in ALLOWED_EXTENSIONS:
            continue

        content = file_path.read_text(encoding="utf-8")
        for chunk in _chunk_text(content, chunk_size=chunk_size, overlap=overlap):
            chunks.append(chunk)
            sources.append(str(file_path))

    return chunks, sources


def build_index(knowledge_dir: str, chunk_size: int, overlap: int) -> KnowledgeIndex | None:
    chunks, sources = _read_knowledge_documents(knowledge_dir, chunk_size=chunk_size, overlap=overlap)
    if not chunks:
        return None

    vectorizer = TfidfVectorizer(stop_words="english", ngram_range=(1, 2), min_df=1)
    matrix = vectorizer.fit_transform(chunks)
    return KnowledgeIndex(chunks=chunks, sources=sources, vectorizer=vectorizer, matrix=matrix)


def retrieve(query: str, top_k: int = 5) -> list[RetrievedChunk]:
    settings = get_settings()
    index = build_index(
        knowledge_dir=settings.rag_knowledge_dir,
        chunk_size=settings.rag_chunk_size,
        overlap=settings.rag_chunk_overlap,
    )
    if index is None:
        return []

    query_vec = index.vectorizer.transform([query])
    scores = linear_kernel(query_vec, index.matrix).flatten()
    top_idx = scores.argsort()[::-1][: max(1, top_k)]

    retrieved: list[RetrievedChunk] = []
    for idx in top_idx:
        score = float(scores[idx])
        if score <= 0:
            continue
        retrieved.append(
            RetrievedChunk(
                source=index.sources[idx],
                score=score,
                text=index.chunks[idx],
            )
        )
    return retrieved


def answer_with_context(question: str, top_k: int = 5) -> tuple[str, list[RetrievedChunk]]:
    chunks = retrieve(question, top_k=top_k)
    if not chunks:
        return "No RAG knowledge documents were found or no relevant context was retrieved.", []

    context = "\n\n".join(
        [f"Source: {chunk.source}\nSnippet: {chunk.text}" for chunk in chunks]
    )

    settings = get_settings()
    if not settings.openai_api_key or OpenAI is None:
        summary = "\n".join(
            [f"- {chunk.source} (score={chunk.score:.3f})" for chunk in chunks]
        )
        return (
            "OpenAI key is not configured. Retrieved relevant context snippets:\n" + summary,
            chunks,
        )

    client = OpenAI(api_key=settings.openai_api_key)
    prompt = (
        "You are an industrial reliability assistant. "
        "Answer the user question using ONLY the context snippets. "
        "If context is insufficient, say what is missing.\n\n"
        f"Question: {question}\n\n"
        f"Context:\n{context}"
    )

    response = client.responses.create(model=settings.llm_model, input=prompt, temperature=0)
    answer = (response.output_text or "").strip()
    if not answer:
        answer = "No answer was generated by the LLM."
    return answer, chunks
